### ISSUE TITLE
Can the results of Network Analysis display as Leaflet Routing Machine style ?

### ISSUE THREAD

**Issue by Giserwu** [jgravois/lrm-esri#3]
Hello ! 
I'm trying to show the results of Network Analysis(VRP) in the style of Leaflet Routing Machine, as shown in the figure, but I don't know how. I wonder if this can be achieved ?
![345](https://user-images.githubusercontent.com/23161877/34561829-c928bb50-f186-11e7-87ef-bb78355e18c9.jpg)

I really appreciate if you can give me some suggestions or example that solves this.
Sorry for the inconveniences and thank you in advance.

**Comment by jgravois** [comment]
in this plugin i am parsing the service results manually and massaging them so that they look like what leaflet routing machine is expecting. you'd have to do something similar for a VRP response, keeping in mind that it has a different signature. 

https://github.com/jgravois/lrm-esri/blob/5f82e3de2ab02e64170f260aee55d025f60cf774/src/esriRouter.js#L225-L263

setting the parameter below will ensure more information is returned.

```js
vrpTask.setParam("directions_style_name", "NA Navigation");
```
